name: Deployment

on:
  workflow_dispatch:
    inputs:
      deployAnnouncements:
        description: 'Announcements to deploy'
        required: true

jobs:
  deploy_webhooks:
    name: Build and deploy webhooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules/
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install Node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy webhooks
        run: npm run deploy
        env:
          ANNOUNCEMENT_ALL: ${{ secrets.WEBHOOK_ANNOUNCEMENT_ALL }}
          ANNOUNCEMENT_POLL: ${{ secrets.WEBHOOK_ANNOUNCEMENT_POLL }}
          ANNOUNCEMENT_STAFF: ${{ secrets.WEBHOOK_ANNOUNCEMENT_STAFF }}
          ANNOUNCEMENT_GOODTOKNOW: ${{ secrets.WEBHOOK_ANNOUNCEMENT_GOODTOKNOW }}
          ANNOUNCEMENT_2026: ${{ secrets.WEBHOOK_ANNOUNCEMENT_2026 }}
          ANNOUNCEMENT_2025: ${{ secrets.WEBHOOK_ANNOUNCEMENT_2025 }}
          ANNOUNCEMENT_2024: ${{ secrets.WEBHOOK_ANNOUNCEMENT_2024 }}
          ANNOUNCEMENT_2023: ${{ secrets.WEBHOOK_ANNOUNCEMENT_2023 }}
          ANNOUNCEMENT_2022: ${{ secrets.WEBHOOK_ANNOUNCEMENT_2022 }}
          DRAFT: ${{ secrets.WEBHOOK_DRAFT }}

          WEBHOOK_AVATAR: ${{ secrets.WEBHOOK_AVATAR }}
          WEBHOOK_NAME: ${{ secrets.WEBHOOK_NAME }}

          DEPLOY_SERVER_ID: ${{ secrets.WEBHOOK_DEPLOY_SERVER_ID }}
          DEPLOY_ANNOUNCEMENTS: ${{ github.event.inputs.deployAnnouncements }}
